import {cases,references} from './cases.js';
import {baseline,initialState,lifting,grade,canSubmit,escapeHtml as esc} from './core.js';

const stages=['Conocer','Explorar','Interpretar','Decidir','Reflexionar'];
const state=Object.fromEntries(cases.map(c=>[c.id,initialState(c.id)]));
let active='office',dialogReturn=null;
const app=document.querySelector('#app');
const current=()=>cases.find(c=>c.id===active);
const num=(x,d=2)=>Number(x).toLocaleString('es-CL',{minimumFractionDigits:d,maximumFractionDigits:d});
const icons={arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',book:'<path d="M12 5v15m0-15C8 2 4 3 2 4v15c3-1 6-1 10 1 4-2 7-2 10-1V4c-2-1-6-2-10 1Z"/>',check:'<path d="m5 12 4 4L19 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',reset:'<path d="M3 11a9 9 0 1 1 2 7M3 4v7h7"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4"/>'};
const icon=(name)=>`<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.info}</svg>`;

function render(focus=false){
 const c=current(),s=state[active];
 app.innerHTML=`<header class="topbar"><a class="brand" href="#" data-action="home" aria-label="Núcleo Vivo Lab, volver al primer caso"><span class="wordmark">NÚCLEO VIVO<span class="brand-mark">LAB</span></span><span class="brand-description">SIMULADOR DE<br>KINESIOLOGÍA</span></a><div class="top-actions"><span class="prototype">Prototipo educativo</span><button class="text-button" data-action="help">${icon('info')}<span>Cómo practicar</span></button><button class="text-button" data-action="sources">${icon('book')}<span>Fuentes</span></button></div></header>
 <main id="main" tabindex="-1" data-area="${c.area==='Ergonomía'?'ergonomia':'ortopedia'}"><div class="workspace-intro"><div><p class="eyebrow">LABORATORIO DE ERGONOMÍA Y ORTOPEDIA</p><h1>Aprende a decidir.<span> Practica con un caso.</span></h1></div><span class="visit-progress">${Object.values(state).filter(x=>x.submitted).length}<span> / 4 casos completados<br>en esta visita</span></span></div>
 <nav class="case-nav" aria-label="Seleccionar caso">${cases.map(x=>`<button class="case-tab ${x.id===active?'active':''}" data-case="${x.id}" aria-current="${x.id===active?'page':'false'}"><span class="case-number">${state[x.id].submitted?icon('check'):x.number}</span><span><small>${x.area}</small><strong>${x.short}</strong></span></button>`).join('')}</nav>
 <div class="workspace"><aside class="case-sidebar"><div class="case-status"><span class="eyebrow">CASO ${c.number}</span><span class="small-tag">${c.level}</span></div><h2>${c.title}</h2><p class="case-duration">${c.time} · Práctica formativa</p><nav class="step-nav" aria-label="Etapas del caso">${stages.map((x,i)=>`<button data-step="${i}" ${i>s.maxStep?'disabled':''} class="step ${s.step===i?'active':''}" ${s.step===i?'aria-current="step"':''}><span>${i<s.maxStep?icon('check'):String(i+1).padStart(2,'0')}</span>${x}</button>`).join('')}</nav><div class="objective">${icon('target')}<h3>Tu objetivo</h3><p>${c.objective}</p></div><button class="reset-case" data-action="restart">${icon('reset')}Reiniciar este caso</button></aside>
 <section class="case-content" aria-labelledby="stage-heading"><div class="stage-topline"><p class="eyebrow">${c.area.toUpperCase()} <span>/</span> ${stages[s.step].toUpperCase()}</p><span class="stage-counter">${s.step+1} de 5</span></div>${s.step===0?history(c,s):s.step===1?laboratory(c,s):s.step===2||s.step===3?decisions(c,s):review(c,s)}</section></div>
 <footer class="site-footer"><span>Núcleo Vivo Lab <span class="footer-divider">/</span> Simulador de Kinesiología</span><span>Casos ficticios · Evaluación formativa provisional</span><a class="back-to-prototypes" href="/prototipos/#kinesiologia">Volver a prototipos</a><button data-action="scope">Alcance de esta versión</button></footer></main>
 <dialog id="modal" aria-labelledby="modal-title"><div class="modal-header"><h2 id="modal-title"></h2><button class="icon-button" data-action="close" aria-label="Cerrar ventana">${icon('close')}</button></div><div id="modal-body"></div></dialog><div class="sr-only" id="live" role="status" aria-live="polite"></div>`;
 if(focus){document.querySelector('#stage-heading')?.focus({preventScroll:true});document.querySelector('.case-content')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
}
function nextButton(s,label='Continuar',extra=''){
 return `<div class="stage-footer"><span>${extra}</span><button class="primary" data-action="next">${label}${icon('arrow')}</button></div>`;
}
function history(c,s){return `<h2 id="stage-heading" tabindex="-1">Conoce a ${c.patient}.</h2><p class="section-lead">${c.brief}</p><div class="history-layout"><div class="patient-card"><div class="patient-id"><span class="initial">${c.patient.slice(0,1)}</span><div><strong>${c.patient}, ${c.age} años</strong><span>${c.role}</span></div></div><blockquote>“${c.quote}”</blockquote><span class="small-tag pale">Paciente ficticio</span><div class="patient-guide"><p>Antes de decidir</p><span>Abre las preguntas para construir tu ficha. Puedes volver a ella en cualquier etapa.</span></div></div><div class="inquiry"><div class="subheading"><h3>¿Qué necesitas saber?</h3><span>${s.facts.length}/${c.facts.length} exploradas</span></div>${c.facts.map(f=>`<details class="fact" data-fact="${f.id}" ${s.facts.includes(f.id)?'open':''}><summary><span>${f.label}</span><span class="fact-plus" aria-hidden="true">+</span></summary><div class="fact-body"><span class="eyebrow">${f.tag}</span><p>${f.text}</p></div></details>`).join('')}</div></div>${nextButton(s,'Ir al laboratorio',s.facts.length?'La ficha conserva lo que has explorado.':'Explora las preguntas antes de pasar al laboratorio.')}`;}
function range(key,label,min,max,step,value,unit='°') {return `<label class="range-control" for="${key}"><span>${label}<output id="out-${key}" for="${key}">${num(value,0)}${unit}</output></span><input id="${key}" type="range" data-lab="${key}" min="${min}" max="${max}" step="${step}" value="${value}" ${state[active].submitted?'disabled':''}><span class="range-extents"><span>${min}${unit}</span><span>${max}${unit}</span></span></label>`;}
function toggle(key,label,value){return `<label class="toggle"><input type="checkbox" data-lab="${key}" ${value?'checked':''} ${state[active].submitted?'disabled':''}><span>${label}</span></label>`;}
function laboratory(c,s){return `<h2 id="stage-heading" tabindex="-1">${c.labTitle}</h2><p class="section-lead">${c.labHint}</p><div class="lab-layout"><div class="visual-column"><div class="lab-canvas"><div class="canvas-toolbar"><span>${c.id==='lifting'?'GEOMETRÍA DE LA TAREA':c.id==='ankle'?'EXAMEN DEL CASO':'MODELO SEGMENTARIO 2D'}</span><span class="small-tag">${c.id==='ankle'?'Datos simulados':'Interactivo'}</span></div><div id="diagram">${diagram(c,s)}</div></div><div id="lab-readout" aria-live="polite">${readout(c,s)}</div></div><div class="lab-controls">${controls(c,s)}</div></div><details class="method-note"><summary>${icon('book')} Cómo interpretar este laboratorio</summary><div>${labMethod(c.id)}${sourceLinks(c.sources)}</div></details>${nextButton(s,'Interpretar el caso','Compara y registra mentalmente qué cambió.')}`;}
function controls(c,s){let p=s.lab; if(c.id==='office')return `<h3>Modifica el puesto</h3>${range('neck','Inclinación del segmento cervical',0,45,1,p.neck)}${range('elbow','Ángulo del codo',70,140,1,p.elbow)}${range('screen','Borde superior / altura de ojos',-30,15,1,p.screen,' cm')}${toggle('feet','Pies con apoyo estable',p.feet)}${toggle('variation','Alternancia de posturas y tareas',p.variation)}<button class="secondary full" data-action="reset-lab" ${s.submitted?'disabled':''}>Recuperar configuración inicial</button>`;
 if(c.id==='lifting')return `<h3>Diseña una alternativa</h3>${range('h','Distancia horizontal de manos · H',25,63,1,p.h,' cm')}${range('v','Altura de manos en origen · V',25,125,5,p.v,' cm')}${range('a','Asimetría · A',0,135,5,p.a)}${range('load','Masa por caja',2,25,1,p.load,' kg')}<label class="select-label" for="frequency">Levantamientos por minuto<select id="frequency" data-lab="frequency" ${s.submitted?'disabled':''}>${[.2,.5,1,2,4].map(f=>`<option value="${f}" ${p.frequency===f?'selected':''}>${num(f,f<1?1:0)} / min</option>`).join('')}</select></label>${toggle('applicable','Se mantiene el uso de dos manos',p.applicable)}<button class="secondary full" data-action="reset-lab" ${s.submitted?'disabled':''}>Recuperar tarea original</button>`;
 return `${c.id==='knee'?`<h3>Explora la geometría</h3>${range('angle','Flexión de rodilla',0,120,1,p.angle)}<p class="control-note">0° representa extensión en este modelo. La figura no es una medición del paciente.</p>`:''}<h3>Selecciona una exploración</h3><div class="exam-list">${c.exam.map(e=>`<button class="exam-button ${p.exam.includes(e.id)?'exam-done':''}" data-exam="${e.id}" ${s.submitted?'disabled':''}><span>${e.label}</span>${icon(p.exam.includes(e.id)?'check':'eye')}</button>`).join('')}</div><p class="control-note">Cada selección revela un hallazgo preparado para este caso.</p>`;
}
function svgStart(label){return `<svg viewBox="0 0 540 370" role="img" aria-label="${label}" class="biomechanics"><defs><pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M30 0H0V30" fill="none" stroke="#d8ddff" stroke-width=".7"/></pattern></defs><rect width="540" height="370" fill="url(#grid)"/>`;}
function diagram(c,s){const p=s.lab;if(c.id==='office'){
 const rad=p.neck*Math.PI/180,nx=190+Math.sin(rad)*45,ny=150-Math.cos(rad)*45,el=p.elbow*Math.PI/180,wx=190+90*Math.sin(el),wy=220-90*Math.cos(el),screenY=ny-17-p.screen*2;
 return `${svgStart(`Esquema del puesto. Segmento cervical a ${p.neck} grados y codo a ${p.elbow} grados.`)}<path d="M90 323H460M310 237h165M440 237v86" class="environment-line"/><path d="M170 178v86h96M183 264v59" class="environment-line"/><path d="M190 249V150L${nx} ${ny}M190 152V220L${wx} ${wy}M190 249h86v63l35 5" class="segment"/><circle cx="${nx}" cy="${ny-17}" r="17" class="head"/><circle cx="190" cy="220" r="6" class="joint"/><circle cx="190" cy="249" r="6" class="joint"/><path d="M190 148v-64M190 220h115" class="reference-line"/><path d="M190 114a36 36 0 0 1 ${Math.sin(rad)*36} ${36-Math.cos(rad)*36}" class="angle-arc"/><rect x="374" y="${screenY}" width="9" height="82" rx="3" fill="#2847ed"/><path d="M378 ${screenY+82}V230h-25" class="environment-line"/><path d="M${nx+22} ${ny-17}H430" class="reference-line"/><text x="235" y="105" class="measure-label">${p.neck}°</text><text x="225" y="204" class="measure-label">${p.elbow}°</text><text x="395" y="${Math.min(285,screenY+50)}" class="small-measure">${p.screen>0?'+':''}${p.screen} cm</text>${p.feet?'<path d="M260 321h60" stroke="#7138d5" stroke-width="7"/>':''}<text x="30" y="350" class="diagram-caption">Ángulos configurados · proporciones esquemáticas</text></svg>`;
 }if(c.id==='lifting'){
 const x=120+p.h*4,yo=310-p.v*1.45,yd=310-(p.v+50)*1.45;
 return `${svgStart('Geometría del levantamiento: distancia horizontal, altura de origen y altura de destino.')}<path d="M70 310H490M120 45V310" class="environment-line"/><path d="M120 ${yo}H${x}M120 ${yd}H${x}M${x} ${yd}V${yo}" class="reference-line"/><rect x="${x-25}" y="${yo-20}" width="50" height="40" rx="4" class="load-box"/><rect x="${x-25}" y="${yd-20}" width="50" height="40" rx="4" fill="none" stroke="#7138d5" stroke-width="2" stroke-dasharray="5 4"/><circle cx="120" cy="310" r="5" class="joint"/><path d="M${x} ${yo-32}V${yd+33}m-6 7 6-7 6 7" class="angle-arc"/><path d="M120 338h${p.h*4}" class="angle-arc"/><text x="${(120+x)/2}" y="360" text-anchor="middle" class="measure-label">H = ${p.h} cm</text><text x="30" y="${yo+5}" class="small-measure">${p.v} cm</text><text x="30" y="${yd+5}" class="small-measure">${p.v+50} cm</text><text x="${x+36}" y="${(yo+yd)/2+5}" class="small-measure">D = 50 cm</text><text x="${x}" y="${yo+5}" text-anchor="middle" class="box-text">${p.load} kg</text><text x="162" y="42" class="small-measure">A = ${p.a}° · ${num(p.frequency,p.frequency<1?1:0)} levant./min</text><text x="70" y="${yd-35}" class="diagram-caption">Destino</text><text x="70" y="${yo+38}" class="diagram-caption">Origen</text></svg>`;
 }if(c.id==='knee'){
 const r=p.angle*Math.PI/180,x=245+125*Math.sin(r),y=170+125*Math.cos(r),ax=245+48*Math.sin(r),ay=170+48*Math.cos(r);
 return `${svgStart(`Goniómetro esquemático, flexión de rodilla de ${p.angle} grados.`)}<path d="M245 50V310" class="reference-line"/><path d="M245 48V170L${x} ${y}" class="segment wide"/><circle cx="245" cy="170" r="13" class="joint"/>${p.angle?`<path d="M245 218A48 48 0 0 0 ${ax} ${ay}" class="angle-arc"/>`:''}<text x="340" y="102" class="big-measure">${p.angle}°</text><text x="340" y="126" class="diagram-caption">Flexión</text><text x="280" y="50" class="small-measure">Segmento proximal</text><text x="95" y="290" class="small-measure">Referencia: 0°</text><text x="30" y="350" class="diagram-caption">Modelo angular · no calcula carga ni presión articular</text></svg>`;
 }return `<div class="exam-overview"><span class="exam-case-number">03</span><span class="eyebrow">TOBILLO DERECHO · 18 HORAS</span><h3>¿Qué hallazgo<br>cambia tu decisión?</h3><p>Explora la sensibilidad ósea, el apoyo y el estado neurovascular antes de elegir una intervención.</p><div class="exam-count"><strong>${p.exam.length}</strong><span>de ${c.exam.length}<br>exploraciones abiertas</span></div></div>`;
}
function readout(c,s){const p=s.lab;if(c.id==='lifting'){
 const r=lifting(p),b=lifting(baseline.lifting);if(!r.valid)return `<div class="feedback-box caution"><strong>Cálculo no aplicable</strong><p>${r.reason}</p></div>`;
 return `<div class="comparison"><div><span>Tarea original · LI</span><strong>${num(b.li)}</strong></div><span class="compare-arrow">${icon('arrow')}</span><div class="comparison-new"><span>Tu rediseño · LI</span><strong>${num(r.li)}</strong></div></div><div class="metric-line"><span>RWL limitante</span><strong>${num(r.rwl)} kg</strong><span>${r.governing}</span></div><p class="control-note">${r.li>1?'La carga supera el límite calculado. Explora qué condiciones puedes modificar.':'La carga no supera el límite calculado en este ejercicio. El resultado no garantiza ausencia de lesión.'}</p><details class="calculation"><summary>Ver los factores y ambos extremos</summary><div class="factor-grid">${Object.entries(r.factors).map(([k,v])=>`<div><span>${k}</span><strong>${num(v,3)}</strong></div>`).join('')}</div><p>RWL origen: ${num(r.origin)} kg · destino: ${num(r.destination)} kg.</p><p>RWL = 23 × HM × VM × DM × AM × FM × CM.<br>LI = masa de la caja / menor RWL.</p></details>`;
 }if(c.id==='office')return `<div class="observation-note"><span class="eyebrow">LEE EL CAMBIO</span><p>${p.elbow>=90&&p.elbow<=120?'El codo está dentro de la referencia de 90°–120° descrita por OSHA.':'Compara el codo con la referencia de 90°–120° de OSHA y observa el alcance real.'} ${p.feet?'Ahora hay apoyo para los pies.':'Revisa la falta de apoyo de los pies.'}</p><p>${p.variation?'El ajuste incluye alternar tareas y posturas.':'La configuración también requiere considerar variación y organización de la jornada.'}</p><span class="control-note">La comodidad y la visión deben comprobarse con la persona; ningún ángulo aislado establece un diagnóstico.</span></div>`;
 return `<div class="findings"><div class="subheading"><h3>Hallazgos disponibles</h3><span>${p.exam.length}/${c.exam.length}</span></div>${p.exam.length?p.exam.map(id=>{const e=c.exam.find(x=>x.id===id);return `<article class="finding ${e.important?'priority-finding':''}"><strong>${e.label}</strong><p>${e.result}</p></article>`;}).join(''):'<p class="empty-note">Selecciona una exploración para revelar su resultado.</p>'}</div>`;
}
function labMethod(id){return id==='lifting'?`<p>Ejercicio acotado de RNLE: caja estable, buen acoplamiento (CM = 1), dos manos, trabajador de pie, piso estable, ambiente confortable, espacio libre y movimiento lento. No incluye transporte, empuje o movilización de personas.</p><p>Duración fija: 30 minutos de tarea y al menos 30 minutos posteriores de trabajo liviano. Frecuencias discretas de 0,2; 0,5; 1; 2 y 4 levantamientos/minuto. Desplazamiento vertical de 50 cm. H y A iguales en origen y destino; ambos requieren control significativo.</p><p>HM = 25/H; VM = 1 − 0,003 × |V − 75|; DM = 0,82 + 4,5/D; AM = 1 − 0,0032 × A. FM corresponde a corta duración. La interfaz restringe los rangos al ejercicio. La tarea real requiere verificar el manual completo.</p>`:id==='office'?`<p>Los ángulos son variables que tú configuras; el simulador no los mide desde una cámara ni predice cómo responderá una persona. La distancia del monitor se expresa respecto de la altura de los ojos.</p><p>Se utilizan referencias de OSHA para explorar el puesto. El caso enseña a seleccionar ROSA, pero no implementa sus tablas ni entrega una puntuación de riesgo.</p>`:id==='ankle'?`<p>Los hallazgos pertenecen a un caso ficticio de lesión aguda en un adulto. Esta versión entrena la priorización de evaluación adicional; no implementa una calculadora universal de las reglas de Ottawa ni confirma fracturas.</p>`:`<p>El ángulo se mide entre la prolongación del segmento proximal y el segmento distal, con 0° como extensión. No es un modelo de fuerzas ni de tejidos. Los hallazgos funcionales están preparados para el caso.</p>`;}
function caseRecord(c,s){return `<details class="record"><summary>${icon('book')} Consultar mi ficha <span>${s.facts.length} antecedentes</span></summary><div>${s.facts.length?s.facts.map(id=>{const f=c.facts.find(x=>x.id===id);return `<p><strong>${f.tag}.</strong> ${f.text}</p>`;}).join(''):'<p>Aún no has abierto antecedentes. Puedes volver a “Conocer”.</p>'}${s.lab.exam?.length?s.lab.exam.map(id=>{const e=c.exam.find(x=>x.id===id);return `<p><strong>${e.label}.</strong> ${e.result}</p>`;}).join(''):''}<button class="secondary" data-step="0">Volver a las preguntas</button></div></details>`;}
function decisions(c,s){const qs=c.questions.filter(q=>q.phase===s.step);return `<h2 id="stage-heading" tabindex="-1">${s.step===2?'Relaciona los hallazgos.':'Decide y explica por qué.'}</h2><p class="section-lead">${s.step===2?'Selecciona la interpretación que puedas sostener con los datos del caso.':'La decisión importa. Tu justificación permite discutir cómo llegaste a ella.'}</p>${caseRecord(c,s)}<div class="questions">${qs.map((q,qi)=>`<fieldset class="question"><legend><span class="question-index">${s.step===2?qi+1:qi+3}</span>${q.text}</legend><div class="options">${q.options.map((o,oi)=>`<label class="option ${s.answers[q.id]===o.id?'selected':''}"><input type="radio" name="${q.id}" value="${o.id}" data-answer="${q.id}" ${s.answers[q.id]===o.id?'checked':''} ${s.submitted?'disabled':''}><span class="option-letter">${String.fromCharCode(65+oi)}</span><span>${o.text}</span></label>`).join('')}</div></fieldset>`).join('')}</div>${s.step===3?`<label class="writing-label" for="rationale">Justifica tu plan<span>Relaciona dos hallazgos con tu decisión e indica qué volverías a evaluar.</span></label><textarea id="rationale" data-writing="rationale" rows="4" maxlength="3000" placeholder="Priorizaría… porque en el caso observé… Para reevaluar…" ${s.submitted?'readonly':''}>${esc(s.rationale)}</textarea><p class="control-note">Tu texto queda en el informe para revisión y discusión; no recibe una nota automática.</p>`:''}<div class="form-error" role="alert">${s.error}</div>${s.submitted?nextButton(s,'Ver mi devolución','Este intento ya fue cerrado. Reinicia para ensayar otra decisión.'):s.step===2?nextButton(s,'Construir mi plan','Elige una respuesta en cada pregunta.'):`<div class="stage-footer"><span>Cuatro decisiones y una justificación.</span><button class="primary" data-action="submit">Cerrar el caso y revisar${icon('arrow')}</button></div>`}`;}
function review(c,s){const r=s.result;if(!r)return '<h2 id="stage-heading">Completa las decisiones para abrir la reflexión.</h2>';
 return `<h2 id="stage-heading" tabindex="-1">Vuelve sobre tus decisiones.</h2><p class="section-lead">Esta devolución corresponde a tu primer cierre de este intento. Úsala para contrastar el razonamiento, no como certificación clínica.</p><div class="review-summary"><div class="review-score"><strong>${r.total}<span>/${r.max}</span></strong><span>Puntos en decisiones<br>del caso</span></div><div><span class="eyebrow">${r.critical?'PRIORIDAD PARA DISCUTIR':'DEVOLUCIÓN FORMATIVA'}</span><h3>${r.critical?'Revisa una decisión de seguridad.':r.total===r.max?'Tus decisiones son coherentes con este caso.':r.total>=r.max/2?'Hay decisiones bien encaminadas y otras por revisar.':'Vuelve a conectar los datos con tu plan.'}</h3><p>${r.critical?'La suma no compensa los aspectos señalados como prioritarios. Revisa su explicación antes de repetir.':'Las explicaciones siguientes muestran qué respalda cada decisión y qué faltó considerar.'}</p></div></div><div class="review-rows">${r.rows.map(row=>`<article class="review-row ${row.critical?'critical':''}"><div><span class="small-tag">${row.dimension}</span><strong class="row-score">${row.score}/2</strong></div><h3>${row.answer}</h3><p>${row.feedback}</p>${row.critical?'<span class="critical-label">Revisión prioritaria</span>':''}</article>`).join('')}</div><div class="rationale-review"><h3>Tu justificación</h3><p>${esc(r.rationale)}</p><span class="control-note">Pendiente de revisión humana. No se evaluó automáticamente la calidad de este texto.</span></div><section class="reflection"><span class="eyebrow">REFLEXIÓN Y TRANSFERENCIA</span><h3>${c.reflection}</h3><p>${c.transfer}</p><label class="sr-only" for="reflection">Tu reflexión final</label><textarea id="reflection" data-writing="reflection" rows="4" maxlength="3000" placeholder="Ahora considero… En el nuevo escenario revisaría…">${esc(s.reflection)}</textarea><p class="control-note">La reflexión se incluye al descargar el informe. El progreso se conserva solo durante esta visita.</p></section><details class="method-note"><summary>Cómo se asignan estos puntos</summary><div><p>Rúbrica original provisional: cada decisión obtiene 0 (no sustentada), 1 (parcial) o 2 (coherente con el caso). No hay punto de aprobación. La justificación y la reflexión necesitan revisión docente.</p><p>Se registraron ${r.observed} de ${r.available} antecedentes antes del cierre. Abrir antecedentes no demuestra por sí solo comprensión y no suma puntos.</p></div></details><div class="case-sources"><h3>Para estudiar este caso</h3>${sourceLinks(c.sources)}</div><div class="stage-footer"><button class="secondary" data-action="download">${icon('download')}Descargar mi informe</button><button class="primary" data-action="next-case">${c.number==='04'?'Volver al primer caso':'Practicar el siguiente caso'}${icon('arrow')}</button></div>`;
}
function sourceLinks(ids){return `<ul class="source-list">${ids.map(id=>{const r=references[id];return `<li><a href="${r.url}" target="_blank" rel="noopener noreferrer">${r.title}<span aria-hidden="true"> ↗</span></a><p>${r.note}</p></li>`;}).join('')}</ul>`;}
function modal(title,body){dialogReturn=document.activeElement;document.querySelector('#modal-title').textContent=title;document.querySelector('#modal-body').innerHTML=body;document.querySelector('#modal').showModal();}
function updateLab(){const c=current(),s=state[active];document.querySelector('#diagram').innerHTML=diagram(c,s);document.querySelector('#lab-readout').innerHTML=readout(c,s);}
function goStep(i){const s=state[active];if(i>s.maxStep)return;s.step=i;s.error='';render(true);}
function error(message){state[active].error=message;const box=document.querySelector('.form-error');if(box){box.textContent=message;box.scrollIntoView({block:'center',behavior:'smooth'});}}
function next(){const c=current(),s=state[active];if(s.submitted&&s.step>=2){s.step=4;render(true);return;}if(s.step===2&&!c.questions.filter(q=>q.phase===2).every(q=>s.answers[q.id])){error('Selecciona una respuesta para cada interpretación antes de continuar.');return;}s.step=Math.min(s.step+1,3);s.maxStep=Math.max(s.maxStep,s.step);s.error='';render(true);}
function selectCase(id){if(!state[id])return;active=id;render(true);}
function report(){const c=current(),s=state[active],r=s.result;if(!r)return;let body=`NÚCLEO VIVO LAB · INFORME DE PRÁCTICA\n${c.title}\nPaciente ficticio: ${c.patient}, ${c.age} años\nCierre: ${new Date(r.completedAt).toLocaleString('es-CL')}\n\nPuntos en decisiones: ${r.total}/${r.max}. Rúbrica provisional, sin punto de aprobación.\n${r.critical?'REVISIÓN PRIORITARIA: hay decisiones de seguridad por discutir.\n':''}\n`;
 body+=r.rows.map((row,i)=>`${i+1}. ${row.dimension} — ${row.score}/2\nPregunta: ${row.question}\nDecisión: ${row.answer}\nDevolución: ${row.feedback}${row.critical?'\nREVISIÓN PRIORITARIA':''}`).join('\n\n');
 body+=`\n\nJUSTIFICACIÓN (requiere revisión humana)\n${r.rationale}\n\nREFLEXIÓN\n${s.reflection||'No registrada.'}\n\nPREGUNTA DE TRANSFERENCIA\n${c.transfer}\n\nEXPLORACIÓN AL CIERRE\nAntecedentes abiertos: ${r.observed}/${r.available}\n`;
 if(c.id==='lifting'){const v=lifting(r.lab);body+=`H: ${r.lab.h} cm; V origen: ${r.lab.v} cm; V destino: ${r.lab.v+50} cm; A: ${r.lab.a}°; masa: ${r.lab.load} kg; F: ${r.lab.frequency}/min.\n`+ (v.valid?`RWL: ${num(v.rwl)} kg; LI: ${num(v.li)}. CM=1; D=50 cm; 30 min de trabajo + >=30 min de recuperación. Control en ambos extremos.\n`:`No aplicable: ${v.reason}\n`);}else if(c.id==='office')body+=`Segmento cervical: ${r.lab.neck}°; codo: ${r.lab.elbow}°; pantalla/ojos: ${r.lab.screen} cm; apoyo de pies: ${r.lab.feet?'sí':'no'}; alternancia: ${r.lab.variation?'sí':'no'}. No es una puntuación ROSA.\n`;else body+=`Exploraciones abiertas: ${r.lab.exam.map(id=>c.exam.find(e=>e.id===id).label).join(', ')||'ninguna'}.\n`;
 body+='\nFUENTES\n'+c.sources.map(id=>references[id].title+'\n'+references[id].url).join('\n\n')+'\n\nUn proyecto de Núcleo Vivo Lab. Casos ficticios, reglas preparadas. No acredita competencia clínica ni reemplaza supervisión. Informe generado localmente en el navegador.\n';
 const url=URL.createObjectURL(new Blob([body],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`Nucleo_Vivo_Lab_Caso_${c.number}_Informe.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#live').textContent='Informe de práctica preparado para descargar.';
}
app.addEventListener('click',event=>{
 const el=event.target.closest('button,a[data-action]');if(!el||el.disabled)return;
 if(el.dataset.case){selectCase(el.dataset.case);return;}
 if(el.dataset.step!==undefined){goStep(Number(el.dataset.step));return;}
 if(el.dataset.exam){const s=state[active];if(s.submitted)return;if(!s.lab.exam.includes(el.dataset.exam))s.lab.exam.push(el.dataset.exam);el.classList.add('exam-done');el.querySelector('svg').outerHTML=icon('check');updateLab();return;}
 const c=current(),s=state[active];switch(el.dataset.action){
 case 'home':event.preventDefault();selectCase('office');break;
 case 'next':next();break;
 case 'submit':if(s.submitted)return;if(!canSubmit(c,s)){error('Completa las cuatro decisiones y escribe una justificación de al menos 15 caracteres. Puedes volver a “Interpretar” si falta una respuesta.');return;}s.result=grade(c,s);s.submitted=true;s.step=4;s.maxStep=4;s.error='';render(true);break;
 case 'restart':modal('Reiniciar este caso',`<p>Se borrarán las decisiones, ajustes y reflexiones de este intento de ${c.patient}. Los otros casos se conservan.</p><div class="dialog-actions"><button class="secondary" data-action="close">Conservar intento</button><button class="primary" data-action="confirm-restart">Reiniciar caso</button></div>`);break;
 case 'confirm-restart':state[active]=initialState(active);render(true);break;
 case 'reset-lab':if(s.submitted)return;s.lab=structuredClone(baseline[active]);render(false);break;
 case 'next-case':selectCase(cases[(cases.findIndex(x=>x.id===active)+1)%cases.length].id);break;
 case 'download':report();break;
 case 'close':document.querySelector('#modal').close();dialogReturn?.focus();break;
 case 'sources':modal('Fuentes para construir tu razonamiento',`<p>Consulta las referencias vinculadas a los casos. La bibliografía orienta las reglas educativas; no implica validación ni aval institucional del simulador.</p>${sourceLinks(Object.keys(references))}`);break;
 case 'help':modal('Tu recorrido de práctica',`<ol class="help-steps"><li><strong>Conocer.</strong> Pregunta y reúne antecedentes del caso.</li><li><strong>Explorar.</strong> Ajusta variables o abre hallazgos de la evaluación.</li><li><strong>Interpretar.</strong> Contrasta explicaciones con la información disponible.</li><li><strong>Decidir.</strong> Elige un plan y justifícalo.</li><li><strong>Reflexionar.</strong> Revisa la devolución y aplica lo aprendido a una variación del caso.</li></ol><p>Puedes cambiar de caso y volver a tu intento durante esta visita. Al recargar o cerrar la página se pierde el progreso; descarga tu informe al terminar.</p><p>Se recomienda discutir la justificación y la transferencia con un docente. Los casos son ficticios y la rúbrica todavía es provisional.</p>`);break;
 case 'scope':modal('Alcance de esta versión',`<p>Este proyecto de Núcleo Vivo Lab es un simulador de práctica para estudiantes de Kinesiología. Contiene cuatro casos ficticios, retroalimentación preparada, un modelo angular y un cálculo RNLE acotado a las condiciones indicadas.</p><p>Las respuestas siguen reglas del caso. No hay un chat de IA generativa ni se capturan imágenes, datos de pacientes o identidades. Las interacciones se mantienen en memoria durante esta visita.</p><p>El laboratorio de oficina no calcula ROSA, RULA ni REBA. Los diagramas no son modelos anatómicos ni predicen dolor, lesión o presión articular. Las decisiones clínicas se trabajan con fines educativos.</p><p>La rúbrica es original y provisional. Esta versión requiere pilotaje y revisión docente antes de utilizarse para calificaciones o investigación de eficacia.</p><p>Base académica preparada el 7 de septiembre de 2026.</p>`);break;
 }
});
app.addEventListener('input',event=>{
 const el=event.target,s=state[active];if(el.dataset.lab&&!s.submitted){s.lab[el.dataset.lab]=el.type==='checkbox'?el.checked:Number(el.value);const out=document.querySelector(`#out-${el.dataset.lab}`);if(out){const unit=['h','v','screen'].includes(el.dataset.lab)?' cm':el.dataset.lab==='load'?' kg':'°';out.textContent=num(Number(el.value),0)+unit;}updateLab();}
 if(el.dataset.writing){if(el.dataset.writing==='rationale'&&s.submitted)return;s[el.dataset.writing]=el.value;}
 if(el.dataset.answer&&!s.submitted){s.answers[el.dataset.answer]=el.value;el.closest('.options').querySelectorAll('.option').forEach(x=>x.classList.toggle('selected',x.querySelector('input').checked));s.error='';const box=document.querySelector('.form-error');if(box)box.textContent='';}
});
app.addEventListener('toggle',event=>{const el=event.target;if(!el.matches('details[data-fact]')||!el.open)return;const s=state[active];if(!s.facts.includes(el.dataset.fact)){s.facts.push(el.dataset.fact);const counter=document.querySelector('.inquiry .subheading span');if(counter)counter.textContent=`${s.facts.length}/${current().facts.length} exploradas`;}},true);
render();
