'use client';
import { useEffect, useState } from 'react';
import { motion, useReducedMotion } from 'motion/react';
const scenes=[{label:'Trabajar mejor',sub:'Personas, organización e IA',title:<>Otra forma de<br/>trabajar empieza<br/><em>con las personas.</em></>,description:'Conectamos estrategia, tecnología y aprendizaje para transformar los desafíos de tu organización en acciones concretas.',image:'nv-tecnologia-en-el-taller.webp',href:'/consultoria/',cta:'Explorar la consultoría'},{label:'Aprender distinto',sub:'Educación y experiencias',title:<>Aprender también<br/>es atreverse<br/><em>a probar.</em></>,description:'Formación, experiencias y simuladores para explorar posibilidades, practicar decisiones y reflexionar sobre lo aprendido.',image:'nv-aprendizaje-en-terreno.webp',href:'/sembrar/',cta:'Descubrir Sembrar'},{label:'Hacer crecer una idea',sub:'Estrategia y tecnología',title:<>Una buena idea<br/>merece espacio<br/><em>para crecer.</em></>,description:'Unimos experiencia comercial y desarrollo tecnológico para llevar una propuesta a una experiencia que puedas usar.',image:'nv-consultoria-mercado-local.webp',href:'/prototipos/',cta:'Entrar a los proyectos'}];
const areas=[['01','Consultoría','Dar dirección al cambio.','Estrategia comercial, desarrollo organizacional e inteligencia artificial aplicada a tu contexto.','/consultoria/'],['02','Sembrar','Aprender haciendo.','Cursos y experiencias para docentes, estudiantes, equipos y comunidades educativas.','/sembrar/'],['03','Núcleo Vivo Lab','Practicar antes de decidir.','Simuladores para explorar entrevistas, situaciones educativas y decisiones de gestión.','/lab/']];
const projects=[['MOVE','Una experiencia que conecta.','Catálogo, atención y agenda en una propuesta comercial interactiva.','/prototipos/move/','/assets/prototipos/move-hero.webp'],['Escucha Viva','Construir una decisión.','Entrevistas simuladas y reflexión para estudiantes de Psicología.','/lab/simulador/','/assets/showcase/originals/escucha-viva-presentacion-oficial.png']];
export default function Home(){const [active,setActive]=useState(0),[menu,setMenu]=useState(false);const reduced=useReducedMotion();useEffect(()=>{const s=document.createElement('script');s.type='module';s.src='/nv-logo-three.js?v=20261004-continuous';document.body.appendChild(s);return()=>s.remove()},[]);const reveal={initial:{opacity:0,y:reduced?0:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.15},transition:{duration:.6}};return <>
<a className="skip" href="#inicio">Saltar al contenido</a>
<header className="header"><a className="brand nv-brand-3d" href="/" aria-label="Núcleo Vivo, inicio"><span className="nv-brand-icon3d"><canvas data-nv-logo-three className="nv-logo-three" aria-hidden="true"/><img className="nv-logo-fallback" src="/assets/nv-isotipo-3d.svg" alt=""/></span><span>núcleo vivo</span></a><button className="menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="navigation">{menu?'Cerrar':'Menú'}</button><nav id="navigation" className={menu?'nav open':'nav'} aria-label="Principal"><a href="/lineas/">Qué hacemos</a><a href="/consultoria/">Consultoría</a><a href="/prototipos/">Proyectos</a><details><summary>Ideas</summary><div className="dropdown"><a href="/cuadernos/">Cuadernos</a><a href="/podcast/">Podcast</a></div></details><details><summary>Acceder</summary><div className="dropdown"><a href="/mi-nucleo/">Mi Núcleo</a><a href="/sembrar/aula/">Mi Aula</a><a href="https://psicoldp-simulador-limpio.vercel.app/">Escucha Viva</a><a href="https://psicoldp.org/umbral/">Umbral Docente</a></div></details><a className="contact" href="/contacto/">Hablemos</a></nav></header>
<main id="inicio"><section className="hero"><div className="hero-images" aria-hidden="true">{scenes.map((s,i)=><img key={s.image} src={'/assets/editorial-2026/'+s.image} className={active===i?'scene active':'scene'} alt="" fetchPriority={i===0?'high':'auto'}/>)}</div><div className="hero-shade"/><div className="hero-content"><span className="eyebrow">ESTRATEGIA · PERSONAS · TECNOLOGÍA</span><motion.div key={active} initial={{opacity:0,y:reduced?0:15}} animate={{opacity:1,y:0}} transition={{duration:.5}}><h1>{scenes[active].title}</h1><p>{scenes[active].description}</p><a className="light-button" href={scenes[active].href}>{scenes[active].cta}</a></motion.div></div><span className="hero-caption">Personas al centro.<br/>Posibilidades en movimiento.</span><div className="choices" role="group" aria-label="Explorar Núcleo Vivo">{scenes.map((s,i)=><button key={s.label} onClick={()=>setActive(i)} aria-pressed={active===i} className={active===i?'choice selected':'choice'}><span className="number">0{i+1}</span><span><strong>{s.label}</strong><small>{s.sub}</small></span><span className="choice-symbol" aria-hidden="true">+</span></button>)}</div></section>
<section className="intro section"><motion.div {...reveal} className="intro-title"><span className="eyebrow">UNA PROPUESTA QUE CONECTA</span><h2>Lo que quieres cambiar<br/>puede empezar aquí.</h2></motion.div><motion.p {...reveal}>Incorporar tecnología, fortalecer un equipo o dar forma a una idea: cada desafío tiene su contexto. Diseñamos el trabajo conectando las capacidades que necesitas.</motion.p></section>
<section className="areas section" aria-label="Ámbitos de trabajo">{areas.map(([n,name,title,copy,href])=><motion.a {...reveal} className="area" href={href} key={name}><div className="area-top"><span>{name}</span><span className="number">{n}</span></div><h3>{title}</h3><p>{copy}</p><span className="area-link">Explorar {name}<span aria-hidden="true">+</span></span></motion.a>)}</section>
<section className="method"><div className="method-photo"><img src="/assets/editorial-2026/nv-aprendizaje-en-terreno.webp" alt="Personas explorando materiales de aprendizaje junto a un jardín" loading="lazy"/></div><motion.div {...reveal} className="method-copy"><span className="eyebrow">NUESTRA FORMA DE TRABAJAR</span><h2>Escuchar.<br/>Construir.<br/><em>Hacer posible.</em></h2><p>Consultoría, desarrollo y aprendizaje forman parte de un mismo proceso. Comprendemos el contexto, acordamos un objetivo y acompañamos la puesta en práctica.</p><a className="text-link" href="/consultoria/">Conocer nuestra consultoría</a></motion.div></section>
<section className="section projects"><motion.div {...reveal} className="section-heading"><div><span className="eyebrow">IDEAS QUE YA PUEDES EXPLORAR</span><h2>De la pregunta<br/>a la experiencia.</h2></div><a className="text-link" href="/prototipos/">Todos los proyectos</a></motion.div><div className="project-grid">{projects.map(([name,title,copy,href,img])=><motion.a {...reveal} className="project" href={href} key={name}><div className="project-image"><img src={img} alt={'Presentación de '+name} loading="lazy"/></div><div className="project-meta"><span>{name}</span><span>Explorar +</span></div><h3>{title}</h3><p>{copy}</p></motion.a>)}</div><motion.a {...reveal} className="lab-link" href="/prototipos/"><span>También en nuestro laboratorio</span><strong>SomnoGraph · Kinesiología · CHISPA · PsicoLDP</strong><span>Explorar proyectos +</span></motion.a></section>
<section className="ideas section"><motion.div {...reveal}><span className="eyebrow">CUADERNOS Y PODCAST</span><h2>Pensar también<br/>es parte de hacer.</h2><p>Ideas y conversaciones sobre educación, trabajo y las experiencias que nos cambian.</p></motion.div><div className="idea-links"><a href="/cuadernos/"><span>01 / Lecturas</span><h3>Cuadernos</h3><p>Personas, aprendizaje y organizaciones.</p></a><a href="/podcast/"><span>02 / Conversaciones</span><h3>Podcast</h3><p>Un espacio para escuchar otras perspectivas.</p></a><a href="/escena-viva/"><span>03 / Experiencias</span><h3>Escena Viva</h3><p>Teatro aplicado al aprendizaje y al encuentro.</p></a></div></section>
<section className="invitation"><motion.div {...reveal}><span className="eyebrow">CONVERSEMOS</span><h2>¿Qué quieres<br/><em>hacer posible?</em></h2><a className="light-button" href="/contacto/">Hablemos de tu proyecto</a></motion.div></section></main>
<footer className="footer"><div><a className="footer-brand" href="/">núcleo vivo</a><p>Personas al centro.</p><a href="mailto:contacto@nucleovivo.net">contacto@nucleovivo.net</a></div><nav aria-label="Pie de página"><a href="/nucleo-operativo/">IA y tecnología</a><a href="/sembrar/">Formación</a><a href="/lab/">Simuladores</a><a href="/contacto/">Contacto</a></nav><div className="footer-bottom"><span>© 2026 Núcleo Vivo SpA</span><a href="/privacidad/">Privacidad</a><a href="/terminos/">Términos</a></div></footer></>}
